name: CI

on:
  push:
    branches: [ AlessianAU-ci-testing ]
  pull_request:
    branches: [ AlessianAU-ci-testing ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        xcode-version: '13.0'

    - name: Build and test 
      run: xcodebuild clean build -project Hangman.xcodeproj -scheme "Hangman (iOS)" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

